### ISSUE TITLE
How about fastText/Probabilistic fastText/ELMo ? Support ?

### ISSUE THREAD

**Issue by taomanwai** [MichaMucha/emstore#3]

**Comment by taomanwai** [comment]
i read src code, it has bool flag fasttext_format XD

**Comment by MichaMucha** [comment]
Hi!

Only .vec files - the .bin files contain the model and therefore work for OOV as well.
I saw that Facebook started releasing the .bin files too, which is really awesome.
You could generate embeddings for OOV words and add them to your .vec 

Good luck with your work

**Comment by taomanwai** [comment]
Thanks
